# Site settings
title: Mj_Sec 이시현 Portfolio
email: your-email@example.com
description: "보안 연구자를 꿈꾸는 이시현의 포트폴리오"
baseurl: ""
url: "https://duduganadi.github.io"

# Author
author:
  name: 이시현
  bio: "Security Researcher & Developer"

# Build settings
markdown: kramdown
